"""Add name column to OrderItem

Revision ID: 742bc8afeea9
Revises: f6d9acb9e474
Create Date: 2025-06-26 01:17:22.818020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '742bc8afeea9'
down_revision = 'f6d9acb9e474'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
