"""add img_url column to orderItem

Revision ID: b94cb8b430d4
Revises: e3b69d9b20c5
Create Date: 2025-06-26 05:06:33.664284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b94cb8b430d4'
down_revision = 'e3b69d9b20c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_column('img_url')

    # ### end Alembic commands ###
