"""Add receipt column to order table

Revision ID: e3b69d9b20c5
Revises: 742bc8afeea9
Create Date: 2025-06-26 01:44:33.369479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3b69d9b20c5'
down_revision = '742bc8afeea9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receipt', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('receipt')

    # ### end Alembic commands ###
